#!/usr/bin/env python3
"""
bootstrap.py — the consistent provisioning step, run once before a mechanism.

Every mechanism needs some secrets/keys to exist *before first run*. Today that
is handled ad-hoc: some values you must invent and export by hand (`SECRET_KEY`,
`JWT_SECRET`, …), others `seed.py` mints on first run (API keys, certs, SVIDs).
This tool makes the "server-held secret" half deliberate and uniform, without
adding a shared runtime dependency to the mechanisms (this repo intentionally
keeps each directory self-contained — see CLAUDE.md).

It provisions the high-entropy secrets an app reads from the environment into a
gitignored `<dir>/.dev-secrets.env`, generating strong values the first time and
reusing them afterwards (idempotent). You then `source` that file and run.

    python bootstrap.py list                 # what each mechanism needs
    python bootstrap.py 26-dynamic-client-registration
    python bootstrap.py 26                    # prefix is enough
    python bootstrap.py --all

Credentials that are *issued* rather than server-held (API keys, SCIM tokens,
PKI certs, SPIFFE SVIDs, the SAML IdP keypair, the OIDC RSA key) stay with
`seed.py` / first-run generation — this tool points at them but does not own
them. See PROVISIONING.md for the full per-layer story.
"""

import os
import secrets
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_FILE = ".dev-secrets.env"

# Secret generators. Both are high-entropy, so downstream code stores only a
# hash where it persists them (slow hashing only helps low-entropy passwords).
_GEN = {
    "hex32": lambda: secrets.token_hex(32),      # 256-bit session/JWT secret
    "urlsafe": lambda: secrets.token_urlsafe(24),  # opaque bearer token
}

# Per mechanism: the env-provided secrets the SERVER holds, and how to mint them.
SECRETS = {
    "02-secrets-transport": {"SECRET_KEY": "hex32"},
    "03-auth-robustness": {"SECRET_KEY": "hex32"},
    "04-web-hardening": {"SECRET_KEY": "hex32"},
    "05-defense-in-depth": {"SECRET_KEY": "hex32"},
    "07-jwt": {"JWT_SECRET": "hex32"},
    "08-token-lifecycle": {"JWT_SECRET": "hex32"},
    "09-oauth2-auth-code-pkce": {"SECRET_KEY": "hex32", "JWT_SECRET": "hex32"},
    "10-openid-connect": {"SECRET_KEY": "hex32"},
    "12-cert-bound-tokens": {"JWT_SECRET": "hex32"},
    "13-dpop": {"JWT_SECRET": "hex32"},
    "14-saml": {"SECRET_KEY": "hex32"},
    "16-totp": {"SECRET_KEY": "hex32"},
    "17-webauthn": {"SECRET_KEY": "hex32"},
    "19-sso-mailbox": {"SECRET_KEY": "hex32", "JWT_SECRET": "hex32"},
    "21-csrf": {"SECRET_KEY": "hex32"},
    "22-xss": {"SECRET_KEY": "hex32"},
    "23-cors-spa": {"API_TOKEN": "urlsafe"},          # app default is weak; override it
    "24-device-grant": {"SECRET_KEY": "hex32", "JWT_SECRET": "hex32"},
    "25-signup-verification": {"SECRET_KEY": "hex32"},
    "26-dynamic-client-registration": {
        "SECRET_KEY": "hex32", "JWT_SECRET": "hex32", "REGISTRATION_TOKEN": "urlsafe",
    },
}

# Material that seed.py / first-run generation owns — pointed at, not provisioned.
NOTES = {
    "01-login-password": "No server secret before 02; seed.py creates the users.",
    "06-api-keys": "API_KEY is issued (and printed once) by seed.py, stored hashed.",
    "07-jwt": "API_KEY is also issued by seed.py, alongside JWT_SECRET here.",
    "08-token-lifecycle": "API_KEY is issued by seed.py.",
    "10-openid-connect": "RS256 signing key auto-generated on first run "
                         "(oidc_private_key.pem); in prod this comes from a KMS/HSM.",
    "11-mtls": "CA + server/client certs are generated by seed.py into CERT_DIR.",
    "12-cert-bound-tokens": "mTLS PKI is generated by seed.py into CERT_DIR.",
    "13-dpop": "API_KEY is issued by seed.py.",
    "14-saml": "IdP signing keypair (idp_key.pem / idp_cert.pem) is generated by seed.py.",
    "15-spiffe": "SVIDs + trust bundle are generated by seed.py into SVID_DIR.",
    "18-scim": "SCIM bearer token is issued (and printed once) by seed.py, stored hashed.",
    "19-sso-mailbox": "RS256 signing key auto-generated on first run.",
    "20-sql-injection": "No secret; seed.py creates the demo data.",
}


def _mechanisms():
    return sorted(d.name for d in ROOT.iterdir()
                  if d.is_dir() and d.name[:2].isdigit() and "-" in d.name)


def _resolve(arg: str) -> str | None:
    """Accept an exact directory name or an unambiguous prefix (e.g. '26')."""
    mechs = _mechanisms()
    if arg in mechs:
        return arg
    matches = [m for m in mechs if m.startswith(arg) or m[3:].startswith(arg)]
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        print(f"'{arg}' is ambiguous: {', '.join(matches)}", file=sys.stderr)
    else:
        print(f"no mechanism matches '{arg}'", file=sys.stderr)
    return None


def _read_existing(path: Path) -> dict:
    values = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line.startswith("export ") and "=" in line:
                name, _, val = line[len("export "):].partition("=")
                values[name.strip()] = val.strip()
    return values


def provision(name: str) -> None:
    reqs = SECRETS.get(name, {})
    note = NOTES.get(name)
    dirpath = ROOT / name
    envpath = dirpath / ENV_FILE

    if not reqs:
        print(f"• {name}: no server-held secret to provision.")
        if note:
            print(f"    ↳ {note}")
        return

    existing = _read_existing(envpath)   # keep prior values -> idempotent
    lines, fresh = [], []
    for var, kind in reqs.items():
        if var in existing and existing[var]:
            value = existing[var]
        else:
            value = _GEN[kind]()
            fresh.append(var)
        lines.append(f"export {var}={value}")

    envpath.write_text("# Provisioned by bootstrap.py — local dev secrets. DO NOT COMMIT.\n"
                       "# In production these come from a secret manager (Vault/KMS/HSM).\n"
                       + "\n".join(lines) + "\n")
    os.chmod(envpath, stat.S_IRUSR | stat.S_IWUSR)   # 0600 — owner-only

    status = f"provisioned {', '.join(fresh)}" if fresh else "reused existing"
    print(f"• {name}: {status} → {name}/{ENV_FILE}")
    if note:
        print(f"    ↳ {note}")


def _print_run_hint(name: str) -> None:
    print(f"\nReady. To run {name}:")
    print(f"  cd {name}")
    print("  python3 -m venv .venv && source .venv/bin/activate")
    print("  pip install -r requirements.txt")
    if SECRETS.get(name):
        print(f"  source {ENV_FILE}")
    print("  python seed.py && python app.py")


def cmd_list() -> None:
    print("Server-held secrets provisioned by this tool (everything else is seed-issued):\n")
    for m in _mechanisms():
        reqs = SECRETS.get(m, {})
        if reqs:
            print(f"  {m:<34} {', '.join(reqs)}")
        else:
            print(f"  {m:<34} (none — see notes)")
    print("\nRun `python bootstrap.py <dir>` to provision one, or `--all` for every mechanism.")


def main(argv: list[str]) -> int:
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(__doc__.strip())
        return 0
    if argv[0] == "list":
        cmd_list()
        return 0
    if argv[0] == "--all":
        for m in _mechanisms():
            provision(m)
        print("\nAll mechanisms provisioned. `source <dir>/.dev-secrets.env` before running each.")
        return 0

    name = _resolve(argv[0])
    if not name:
        return 2
    provision(name)
    _print_run_hint(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
